Feature/profile edit
oku-053/Twitter_clone pull request #10
Opened 2022-06-23 08:17 UTC by oku-053

【実装した機能】
5.2	ユーザー編集

【やったこと】
- ユーザープロフィール編集画面の作成
- プロフィール編集機能
- 整形ツール導入によるbladeファイルの整形

【変更内容】
プロフィール変更画面
<img width="1439" alt="スクリーンショット 2022-06-23 16 50 09" src="https://user-images.githubusercontent.com/104975290/175251148-77f086aa-7a32-4411-ad25-1a317366ca92.png">

変更後画面
<img width="1133" alt="スクリーンショット 2022-06-23 16 50 32" src="https://user-images.githubusercontent.com/104975290/175251234-fc05204f-23b9-47e8-8ce5-526d62bb4083.png">

2022-06-23 10:38 UTC, ryo-ebata requested changes

2022-06-23 10:38 UTC, ryo-ebata commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
マジックナンバーは避けてね！

2022-06-23 12:37 UTC, oku-053 commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
今回はlaravelデフォルトの記述でこのような値になっている箇所なんだけど、そのような場合はどんなふうに定義するのがベストとかある？
自分で記述した定数の場合は、configファイルで定義したものを呼び出す形にしてます！今回の場合はそれに合わせて書き換えても問題ないかな？

2022-06-23 14:29 UTC, ryo-ebata approved these changes

2022-06-24 02:45 UTC, TairaNozawa commented on app/app/Models/User.php
> +            $this::where('user_id', $this->user_id)
`$this::`
という書き方をあまりみたことがありません！
`$this->`
もしくは
`self::`
になる気がします。

もし`$this::`という書き方があったら教えて下さい！（自分自身最近laravelにふれることが少なく、キャッチアップできていない部分が多々あるので…）

2022-06-24 02:45 UTC, TairaNozawa commented on app/resources/views/home.blade.php
> +    <div class="container">
もしインデントがタブだったらスペース４つにしましょう！
他の箇所も確認お願いします！

2022-06-24 02:51 UTC, TairaNozawa commented on app/app/Models/User.php
> +                ]);
=>からの部分、揃えなくて良いです！
```
->update([
     'name'  => $params['name'],
     'profile_image' => basename($file_name),
      'email'  => $params['email'],
  ]);
```
こんな感じで良いです！

2022-06-24 02:51 UTC, TairaNozawa commented on app/app/Models/User.php
> +                ]);
```
'name' => $params['name']
```
上記のように左側のキーと=>の間に半角スペース、=>と$params['name']の間に半角スペースという感じで大丈夫です！

2022-06-24 03:04 UTC, TairaNozawa commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
$request->user()でとってきたインスタンスにuser_idというプロパティが存在するのか疑問に思いました！
（usersテーブルにuser_idカラムが存在している？）

それとlaravel8についてキャッチアップできていなくて恐縮なのですが、
https://zenn.dev/naoki_oshiumi/articles/e7a1e97ba858b4
https://bashalog.c-brains.jp/20/12/25-170000.php
https://qiita.com/entokyo/items/c9c08ea02bb523b1e3d1
他の記事を呼んでいると
`optional($request->user())->id`
のように書いてある記事が多いのですがoptionalを使わなくても大丈夫でしょうか？

2022-06-24 03:04 UTC, TairaNozawa commented on app/resources/views/users/index.blade.php
> +                                        {{ csrf_field() }}
{{csrf_field()}}は@csrfと同じ意味で@csrfが新しい書き方だと思うので@csrfに合わせたほうが良いと思いました！

2022-06-24 03:04 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
usersテーブルにuser_idカラムが存在すると思うのですがこのカラムはusersの主キーの値が入るカラムでしょうか？
基本usersテーブルにuser_idというカラムが存在するケースはあまりなく違和感を感じました！

2022-06-24 03:09 UTC, oku-053 commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
たしかにキリなくなっちゃうかもね、とりあえず今回はこのままいきます！
マジックナンバーを避けるやり方をいくつかまた調べてみる！

2022-06-24 03:19 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
Userモデルみにいきました。
主キーが入るカラムだったんですね。

2022-06-24 03:19 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
ここはuser_idにカラムを変更した理由などあるのでしょうか？

2022-06-24 03:24 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
今マイグレーションファイルをみてきたのですが基本【テーブルの単数_id】を主キーにしているのでその方針がちゃんと定まっているのであれば良いと思いました！

自分が今まで携わった案件では全てのテーブルで主キーが入るカラムはidとなっていました。

2022-06-24 03:28 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
https://qiita.com/kd9951/items/d6b1cc80188751ce1d2c
主キーはテーブル名＋IDのほうがいい説もあるな…

2022-06-24 03:34 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
全てのテーブルにIDをふるっている【IDリクワイアド】っていうアンチパターンがあってそれを避けるための意図で【テーブル名＋ID】のカラムに変更したのであればそれはあんまり対応しなくてよかった可能性がありますね…

https://zenn.dev/sadayoshitada/scraps/90994e38251f0c#%E3%82%A2%E3%83%B3%E3%83%81%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%82%92%E7%94%A8%E3%81%84%E3%81%A6%E3%82%82%E3%82%88%E3%81%84%E5%A0%B4%E5%90%88
ORMを利用する上で主キーが入るのがidだというのは都合が良く…

2022-06-24 03:50 UTC, TairaNozawa commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
$request->user()でとってきたインスタンスにuser_idというプロパティが存在するのか疑問に思いました！
（usersテーブルにuser_idカラムが存在している？）

> 

ここらへんは気にしないでください！
結論、今のままで大丈夫です！
（https://github.com/oku-053/Twitter_clone/pull/10#discussion_r905687474）

2022-06-24 03:52 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
結論、自分の携わってきたプロジェクトだとtable：テーブル名複数、主キー：id　がたまたま多かっただけで、主キーをテーブル名単数_idとおくパターンも結構あるのでどちらでも大丈夫です！

2022-06-24 07:17 UTC, oku-053 commented on app/app/Models/User.php
> +            $this::where('user_id', $this->user_id)
ネットからこの関数に近い機能を書いているコードをトレースして書いていました！確かに、アローで書くほうが一般的な認識です。トレース元がこのようにしている理由はわからないので、他のコードに合わせて`$this->`に統一します！

2022-06-24 07:43 UTC, oku-053 commented on app/app/Models/User.php
> +        if (isset($params['profile_image'])) {
現状の仕様では新しくアカウントを作った場合、プロフィール画像のカラムは空欄の状態で登録されます。そのため、プロフィール更新時に新しい画像を登録していなくても更新処理が問題ないようにissetにしてみました。

2022-06-24 07:51 UTC, oku-053 commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
usersテーブルの主キーカラムをuser_idとしてDBを設計しています。（この理由は、int型のidをuserの主キーにしているとDBテーブル間で関係が分かりづらい、ルーティングで呼び出すキーが数字だとユーザーにわかりにくい、この2つの理由を考えたからです）なのでusersテーブルにはidというカラムを設けていません。

RouteServiceProviderはそれに合わせてid部分を修正したという経緯です。
ですが、これで動作するのか正確にテストできていないので、これでいいのかなんとも言えない状態です。

2022-06-24 08:06 UTC, oku-053 commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
複数ソースまで出してくださりありがとうございます！

主キーの命名をテーブル名_idにした自分なりの考えとしては上記コメントで少し書きましたが、
自分のDB設計では同じテーブルの中にツイート、コメント、いいねなど複数のテーブルのidを保存するカラムが存在する。そのため、idのままだとコードを書く中でこんがらがってしまいました。なので、各テーブルの主キー名を固有のもに変えてみました。

他のDB設計の記事などを見てみるとテーブル名_idの記述をいくつか見かけましたが、主キーのネーミングはid単体の方が多い印象です。アンチパターンの話は知らないものだったので勉強になりました！

とりあえず、今回の課題ではこのままの設計で進めてみます！

2022-06-24 08:28 UTC, TairaNozawa commented on app/app/Models/User.php
> +        if (isset($params['profile_image'])) {
なるほど！
そうだった場合はprofile_imageの方のカラムをnullableにしてデフォルト値もnullを入れるようにしてif(empty($params['profile_image']))としたほうが良いかもしれないと思いました！
直感的にnullのほうがプロフィール画像が登録されていないっていうメッセージが強くなると思います！

2022-06-24 08:37 UTC, TairaNozawa commented on app/app/Models/User.php
> +        if (isset($params['profile_image'])) {
なるほど！

2022-06-24 08:48 UTC, TairaNozawa commented on app/app/Providers/RouteServiceProvider.php
> +            return Limit::perMinute(60)->by($request->user()?->user_id ?: $request->ip());
なるほど！
しっかり考えられていて良いと思いました！

2022-06-24 08:53 UTC, TairaNozawa commented on app/resources/views/users/show.blade.php
> +                                <span class="text-secondary">{{ $user->user_id }}</span>
総じてDBの設計を自分の頭で考えられていてよかったと思いました！
ちゃんと主キーがテーブル名単数_idにしている理由、主キーの型をstringにしている理由などが明確に説明できていてよかったです！

あとついでに、主キーの話でいうと
https://zenn.dev/dowanna6/articles/3c84e3818891c3
みたいな話があったりするのでそこらへんも調べてみると面白いかもしれません！

2022-06-24 08:56 UTC, TairaNozawa commented on app/app/Models/User.php
> +        if (isset($params['profile_image'])) {
なるほど！

2022-06-24 09:02 UTC, merged

2022-06-24 10:34 UTC, hosaka555 commented on app/app/Models/User.php
> +        return;
このreturnは必要ないかも！

2022-06-24 10:34 UTC, hosaka555 commented on app/database/seeders/TweetsTableSeeder.php
> +                'text'       => 'テスト投稿' .$i,
他にもPHPは[式展開](https://qiita.com/tadsan/items/e4796449c736cfb5c9bd#php%E3%81%A7%E3%81%AF)できるのでこんな感じにもかけます

```php
                'user_id'    => "test_user{$i}",
                'text'       => "テスト投稿{$i}",
```

2022-06-24 10:34 UTC, hosaka555 commented
マージされた後でしたが、気になったところ合ったのでレビューしました