Feature/users2
oku-053/Twitter_clone pull request #5
Opened 2022-06-11 09:41 UTC by oku-053

**【実装した機能】**
- 3.1.2ユーザー一覧
- 3.1.4ツイート新規作成画面へのリンク
- 3.2ユーザー全体を表示
- 3.3各ユーザーの詳細画面へのリンク
- 3.4各ユーザーのフォロー、フォロー解除

**【やったこと】**
- DBのツイート、フォロー、いいね、コメントのテーブル作成
- ユーザー一覧表示
- 一覧表示からフォロー&フォロー解除

**【変更内容】**
ユーザー一覧表示画面
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/104975290/170624969-25b00515-1847-49fa-a735-f21084a8801d.png">

**【特にレビューしてほしいところ】**
- web.phpのルーティング関連で,ログインしているユーザー限定のルートに変えてみました。

2022-06-13 04:55 UTC, ryo-ebata requested changes
何点かコメントしました！
プルリクを出す前に一度自分でも見直してみてね！

2022-06-13 04:55 UTC, ryo-ebata commented on app/app/Http/Controllers/HomeController.php
> +
不要な改行はなくそう！

2022-06-13 04:55 UTC, ryo-ebata commented on app/app/Models/Follower.php
> +    ];
できる限り複合主キーは避けよう！
https://torazuka.hatenablog.com/entry/20110713/pk

2022-06-13 04:55 UTC, ryo-ebata commented on app/app/Http/Controllers/UsersController.php
> +            // フォローしていなければフォローする
いらないコメントは削除しよう！
コメントの書き方はphpDocを活用しよう！
https://tech-blog.rakus.co.jp/entry/20210326/php

2022-06-13 04:55 UTC, ryo-ebata commented on app/app/Models/User.php
> +        return $this->Where('user_id', '<>', $user_id)->paginate(5);
マジックナンバーは定数として定義して避けよう！
https://yutaro-blog.net/2021/05/01/magic-number-laravel/

2022-06-13 04:55 UTC, ryo-ebata commented on app/app/Models/User.php
> +
この辺のコメントも修正して！

2022-06-13 04:55 UTC, ryo-ebata commented on app/database/migrations/2014_10_12_000000_create_users_table.php
> +
ここのインデントも必要ないかな！
自動整形ツールを入れると勝手に改行やインデントを消してくれるから調べてみて！

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/auth/register.blade.php
> +                            <label for="name" class="col-md-4 col-form-label text-md-end">{{ __('user_id') }}</label>
ここ、`user_id`の入力欄だと思うんだけど、`for="name"`でいいのかな？

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
> -                <div class="col-md-4">中央カラム</div>
日本語化は`<a>ホーム</a>`ではなく、`<a>{{ __("'Home') }}</a>`として`ja/ja.json`に記述しよう！
https://qiita.com/mitashun/items/160784ce352cf529f853

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
> +                    右カラム
これだと右カラムって表示されてしまいそうだけど、いいのかな？
必要ないのであれば削除してね！

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
>          </main>
HTMLタグの階層階層合ってなくない？
閉じタグ忘れか整形出来てないかだと思うので、自動整形ツールや閉じタグを自動で入れてくれる拡張ツールを使おう！

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/users/index.blade.php
> +                                        <button type="submit" class="btn btn-primary">フォロー</button>
このファイルも、`<button>{{ __('Follow') }}</button>`と書いて`ja/ja.json`で日本語化しよう！

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/users/show.blade.php
> +                                    <span class="text-secondary">他人のアカウントですよ</span> --}}
必要ないコメント！

2022-06-13 04:55 UTC, ryo-ebata commented on app/resources/views/users/show.blade.php
> +                                        <span class="mt-2 px-1 bg-secondary text-light">フォローされています</span>
日本語化！

2022-06-13 05:11 UTC, ryo-ebata requested changes
ごめん、2つ追記！
・各ページへのリンクはヘッダーじゃなくていい？
・ページネーションのデザイン崩れの修正依頼

よろしくお願いします！

2022-06-13 05:11 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
>  </body>
ごめん！画像見たんだけど、それぞれのページへのリンクはヘッダーじゃなくていいのかな？
意図してるなら大丈夫！

2022-06-13 05:13 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
> +                    右カラム
画像今見ました！
基本的に必要ないなら消してほしいです！

2022-06-13 05:26 UTC, ryo-ebata requested changes

2022-06-13 05:26 UTC, ryo-ebata commented on app/resources/views/users/index.blade.php
> +                                    <form action="{{ route('follow', ['user' => $user->user_id]) }}" method="POST">>
formタグの最後に`>`が連続してるから、気をつけてね

2022-06-13 23:38 UTC, oku-053 commented on app/app/Http/Controllers/UsersController.php
> +            // フォローしていなければフォローする
phpDoc勉強してみます！ありがとう！

2022-06-14 06:49 UTC, oku-053 commented on app/resources/views/layouts/app.blade.php
>  </body>
現在のツイッターのヘッダーの形に近づけようとしてみた。それでヘッダーではなく、カラムを分けてヘッダーにしたんだけど、どうだろうか？

2022-06-14 08:26 UTC, oku-053 commented on app/app/Models/Follower.php
> +    ];
複合主キーとは何なのか、なぜ避けるべきなのか知ることができた！！
ただ、今回のDB設計ではどのようにして回避すればいいのか,代替の実装はできてない。もう少し調べて、必要があればDB設計を見直します！

2022-06-14 10:53 UTC, ryo-ebata commented on app/resources/views/layouts/app.blade.php
>  </body>
なるほど確かにWEB版Twitterはそうやね！
ならいいと思う！

2022-06-14 11:09 UTC, ryo-ebata approved these changes
確認しました！
ひとつだけコメントしたんだけど、修正ではないので承認します！
次のステップに進んでください！

2022-06-14 11:23 UTC, oku-053 commented on app/app/Providers/AppServiceProvider.php
> +        Paginator::useBootstrap();
たしかに必要だね、社員さんへのレビュー依頼にはコメントで最新の画面スクショ載せます！

2022-06-14 12:57 UTC, oku-053 commented
PRのコメントから日本語化を行ったので、最新の状態の画面のスクショです。
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/104975290/173582039-fe90ca08-11c9-4797-ba96-24bd08347718.png">
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/104975290/173582213-1cc596ca-dffa-4c28-8f3a-c042f1c93d50.png">

2022-06-15 02:09 UTC, nakano0531 commented on app/app/Models/Tweet.php
> +    protected $fillable = [
$fillableでも問題はないけど、カラムが増えていくと、
$fillableの値をを増やしていくの大変だよって話は覚えておこう！

$guarded で 更新したくないカラムを以下のように指定すると
protected $guarded = [
    'id',
];
カラムが増えた時に毎回追記する必要は無くなる。
これはプロジェクトの方針による。

https://qiita.com/toro_ponz/items/b33c757cb7ba5bb48ed4

2022-06-15 02:09 UTC, nakano0531 commented on app/resources/views/layouts/app.blade.php
> +                            <a class="nav-link" href="/home">{{ __('Home') }}</a>
他と合わせて、route( {パラメータ名} )を指定した方が良き
他もね

2022-06-15 07:38 UTC, oku-053 commented on app/app/Models/Tweet.php
> +    protected $fillable = [
ありがとうございます！
カラムが増えていく場合を気にせず$fillableを使っていたので、$guardedも選択肢として考えられるように覚えておきます！

2022-06-15 10:35 UTC, merged